services:
  reverse-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: Reverse-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PATH=/.well_known
    volumes:
      - /volumes/nginx/certs:/etc/nginx/certs:ro
      - /volumes/nginx/vhostd:/etc/nginx/vhost.d
      - /volumes/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro

  lets-encrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: 'Lets-Encrypt'
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=Reverse-proxy
    volumes:
      - /volumes/nginx/certs:/etc/nginx/certs
      - /volumes/nginx/vhostd:/etc/nginx/vhost.d
      - /volumes/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  tienda:
    image: pabloalonso24/proyecto-mongo-tiendavideojuegos:latest
    container_name: tiendaApi
    expose:
      - "3000"
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PATH: /
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${USER_EMAIL}
    env_file:
      - .env